remove __del__() function as it was causing an error in my test regarding AttributeError: 'AllBranchesCommitsGetter' object has no attribute 's'. Commenting this out fixed it, but I'm not certain whether to replace/remove completely this function yet, so leaving as reminder